parameters:
#    dan_user.example.class: Dan\UserBundle\Example

services:
#    dan_user.example:
#        class: %dan_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
